// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://afgruahlfvcdtpvnoyfo.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZ3J1YWhsZnZjZHRwdm5veWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA0MjU4NDcsImV4cCI6MjA0NjAwMTg0N30.ROFDipfdExWsGC6ZPK0cnl3-wvzQAijWcaMyp85OKlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);